# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-14 17:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('ApellidoPaterno', models.CharField(max_length=25)),
                ('ApellidoMaterno', models.CharField(max_length=25)),
                ('Correo', models.CharField(max_length=25)),
                ('DNI', models.CharField(max_length=8)),
                ('Telefono', models.CharField(max_length=9)),
                ('Cargo', models.CharField(max_length=25)),
                ('FechaIngreso', models.DateField()),
                ('Estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Correo', models.CharField(max_length=35)),
                ('Password', models.CharField(max_length=25)),
                ('FechaRegistro', models.DateField()),
                ('Trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Trabajador')),
            ],
        ),
    ]
