# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-15 18:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Administracion', '0003_auto_20180515_1300'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Password', models.CharField(max_length=25)),
                ('FechaRegistro', models.DateField()),
                ('Correo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Administracion.Trabajador')),
            ],
        ),
    ]
