# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-05-12 02:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FechaIngreso', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProducto', models.CharField(max_length=35)),
                ('Unidad', models.PositiveSmallIntegerField()),
                ('Estado', models.BooleanField(default=True)),
                ('Categoria', models.CharField(choices=[('LACTEOS', 'lagteos'), ('GALLETAS', 'galletas'), ('GOLOSINAS', 'golosinas'), ('CONCERVAS', 'concerva'), ('BEBIDAS', 'bebidas'), ('OTROS', 'otros')], default='LASTEOS', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NombreProveedor', models.CharField(max_length=35)),
                ('Ruc', models.CharField(max_length=11)),
                ('Direccion', models.CharField(max_length=35)),
                ('Telefono', models.CharField(max_length=9)),
                ('DatosEncargado', models.CharField(max_length=35)),
                ('TelefonoEncargado', models.CharField(max_length=9)),
                ('FechaRegistro', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='ingreso',
            name='Producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.Producto'),
        ),
        migrations.AddField(
            model_name='ingreso',
            name='Proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Almacen.Proveedor'),
        ),
    ]
