# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-14 06:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0003_auto_20180614_0109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salida',
            old_name='PrecioCon',
            new_name='PrecioCom',
        ),
    ]
