# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-27 05:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0004_auto_20180614_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ingreso',
            name='FechaIngreso',
            field=models.DateField(),
        ),
    ]
