# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-05 05:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Almacen', '0002_auto_20180512_2034'),
        ('Venta', '0003_auto_20180604_2206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ventafactura',
            name='Producto',
        ),
        migrations.AddField(
            model_name='ventafactura',
            name='Producto',
            field=models.ManyToManyField(to='Almacen.Salida'),
        ),
    ]
