# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-14 06:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0004_auto_20180605_0018'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nombre', models.CharField(max_length=25)),
                ('Apellidos', models.CharField(max_length=25)),
                ('DNI', models.CharField(max_length=8)),
                ('Sexo', models.CharField(choices=[('M', 'masculino'), ('F', 'femenino')], default='masculino', max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='ventafactura',
            name='Producto',
            field=models.ManyToManyField(blank=True, to='Almacen.Salida'),
        ),
        migrations.AddField(
            model_name='ventafactura',
            name='Cliente',
            field=models.ForeignKey(default=9, on_delete=django.db.models.deletion.CASCADE, to='Venta.Cliente'),
            preserve_default=False,
        ),
    ]
