# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-14 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0005_auto_20180614_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='ventafactura',
            name='Igv',
            field=models.PositiveSmallIntegerField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ventafactura',
            name='dd',
            field=models.PositiveSmallIntegerField(default=99),
            preserve_default=False,
        ),
    ]
