# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2018-06-14 06:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Venta', '0007_division'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Division',
        ),
        migrations.RemoveField(
            model_name='ventafactura',
            name='dd',
        ),
    ]
